# syntax=docker/dockerfile:1
FROM ubuntu:22.04
RUN apt update
RUN apt -y install texlive-latex-recommended
RUN apt -y install texlive-latex-extra
RUN apt -y install texlive-bibtex-extra
RUN apt -y install texlive-lang-german
RUN apt -y install inkscape
RUN apt -y install biber
RUN apt -y install python3-pygments
